### ISSUE TITLE
Endpoints should throw 403 Forbidden instead of 401 Unauthorized

### ISSUE THREAD

**Issue by chownces** [source-academy/backend#956]
Ctrl-F `lib/cadet/assessments` for `:unauthorized`.

Necessary to ensure refresh auth flow works correctly.

**Comment by RichDom2185** [comment]
Technically speaking, if the session token has expired, wouldn't the correct error message be 401 Unauthorized? As opposed to 403 Forbidden, which would generally indicate that the user has insufficient authorization rights to view the content

**Comment by chownces** [comment]
Yup agreed, however I'm referring specifically to the assessment model which is currently throwing 401 when it should be 403
